### ISSUE TITLE
The code seems nothing to do with the green colour of the skin?

### ISSUE THREAD

**Issue by iluvrachel** [mossblaser/HeartMonitor#3]
i don't see any operate on a specific colour channel.
Just simply perform a FFT on the frame?

**Comment by mossblaser** [comment]
The green channel is pulled out specifically in the `sample_frame` method which is where the forehead pixels are turned into a single number which is in turn fed into the FFT.

Hope that answers your question!(?)

**Comment by iluvrachel** [comment]
Sorry, i ignored that part just now , thank u
